# Generated by Django 2.2 on 2019-09-29 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_posicoes_desafio', models.SmallIntegerField(verbose_name='Limite de posições para desafiar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoConfiguracaoLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_posicoes_desafio', models.SmallIntegerField(verbose_name='Limite de posições para desafiar')),
                ('data_hora', smashLadder.utils.DateTimeFieldTz(auto_now_add=True, verbose_name='Data e hora do resultado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_alteracao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
