# Generated by Django 2.2 on 2019-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_auto_20190929_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoconfiguracaoladder',
            name='melhor_de',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Limite máximo de partidas em um desafio'),
        ),
    ]
