# Generated by Django 2.2 on 2019-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0003_historicoconfiguracaoladder_melhor_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoladder',
            name='melhor_de',
            field=models.SmallIntegerField(default=5, verbose_name='Formato melhor de'),
        ),
    ]
