# Generated by Django 2.2 on 2019-12-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0004_auto_20191007_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoladder',
            name='periodo_season',
            field=models.SmallIntegerField(choices=[(1, 'Trimestral'), (2, 'Quadrimestral'), (3, 'Semestral')], default=1, verbose_name='Período de uma Season'),
        ),
    ]
