# Generated by Django 2.2 on 2019-12-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_configuracaoladder_periodo_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoladder',
            name='abonar_primeiro_decaimento',
            field=models.BooleanField(default=True, verbose_name='Abonar primeiro decaimento?'),
        ),
        migrations.AddField(
            model_name='configuracaoladder',
            name='periodo_inatividade',
            field=models.SmallIntegerField(default=30, verbose_name='Período de inatividade para cair'),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoladder',
            name='abonar_primeiro_decaimento',
            field=models.BooleanField(blank=True, null=True, verbose_name='Abonar primeiro decaimento?'),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoladder',
            name='periodo_inatividade',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Período de inatividade para cair'),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoladder',
            name='periodo_season',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Período de uma Season'),
        ),
        migrations.AlterField(
            model_name='historicoconfiguracaoladder',
            name='melhor_de',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Formato melhor de'),
        ),
    ]
