# Generated by Django 2.2 on 2019-12-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_configuracaoladder_periodo_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoladder',
            name='periodo_season',
            field=models.SmallIntegerField(choices=[(0, 'Indeterminado'), (1, 'Trimestral'), (2, 'Quadrimestral'), (3, 'Semestral')], default=0, verbose_name='Período de uma Season'),
        ),
    ]
