# Generated by Django 2.2 on 2019-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0006_auto_20191230_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoladder',
            name='uso_coringa',
            field=models.BooleanField(default=True, verbose_name='Permitido coringa?'),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoladder',
            name='uso_coringa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Permitido coringa?'),
        ),
    ]
