# Generated by Django 2.2 on 2019-08-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogadores', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorTorneio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do jogador')),
                ('posicao_final', models.SmallIntegerField(verbose_name='Resultado no torneio')),
                ('valido', models.BooleanField(default=True, verbose_name='Jogador válido?')),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.SmallIntegerField(verbose_name='Resultado do jogador 1')),
                ('score_2', models.SmallIntegerField(verbose_name='Resultado do jogador 2')),
                ('ganhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhador', to='torneios.JogadorTorneio')),
                ('jogador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador_1', to='torneios.JogadorTorneio')),
                ('jogador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador_2', to='torneios.JogadorTorneio')),
            ],
        ),
        migrations.CreateModel(
            name='VitoriaAusencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torneios.Partida')),
            ],
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do torneio')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do torneio')),
                ('url', models.URLField(verbose_name='URL do torneio')),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do time')),
            ],
            options={
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.SmallIntegerField(verbose_name='Índice do round')),
                ('nome', models.CharField(default='', max_length=20, verbose_name='Nome do round')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.Torneio')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.Round'),
        ),
        migrations.AddField(
            model_name='jogadortorneio',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneios.Time'),
        ),
        migrations.AddField(
            model_name='jogadortorneio',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.Torneio'),
        ),
        migrations.AlterUniqueTogether(
            name='jogadortorneio',
            unique_together={('nome', 'torneio', 'time'), ('jogador', 'torneio')},
        ),
    ]
