# Generated by Django 2.2 on 2019-08-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadortorneio',
            name='id_no_torneio',
            field=models.IntegerField(default=0, verbose_name='Código de identificação no torneio'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('indice', 'torneio')},
        ),
    ]
