# Generated by Django 2.2 on 2019-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0014_feedback'),
        ('torneios', '0003_auto_20190825_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogadortorneio',
            old_name='id_challonge',
            new_name='id_site',
        ),
        migrations.RenameField(
            model_name='torneio',
            old_name='id_challonge',
            new_name='id_site',
        ),
        migrations.AddField(
            model_name='jogadortorneio',
            name='seed',
            field=models.SmallIntegerField(default=0, verbose_name='Seed'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jogadortorneio',
            unique_together={('id_site', 'torneio'), ('jogador', 'torneio'), ('nome', 'torneio', 'time'), ('seed', 'torneio')},
        ),
        migrations.AlterUniqueTogether(
            name='torneio',
            unique_together={('id_site',), ('url',), ('nome', 'data')},
        ),
    ]
