# Generated by Django 2.2 on 2019-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0004_auto_20190827_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadortorneio',
            name='id_site',
            field=models.IntegerField(verbose_name='Código de identificação no site'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='id_site',
            field=models.IntegerField(verbose_name='Código de identificação no site'),
        ),
    ]
