# Generated by Django 2.2 on 2019-09-06 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0005_auto_20190827_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadortorneio',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneios.Time'),
        ),
    ]
