# Generated by Django 2.2 on 2019-04-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogadores', '0002_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da luta')),
                ('ganhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio_coringa', models.BooleanField(verbose_name='É desafio coringa?')),
                ('score_desafiante', models.SmallIntegerField(verbose_name='Vitórias do desafiante')),
                ('score_desafiado', models.SmallIntegerField(verbose_name='Vitórias do desafiado')),
                ('data_hora', models.DateTimeField(verbose_name='Data/hora aproximada do resultado')),
                ('admin_validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('desafiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafiado', to='jogadores.Jogador')),
                ('desafiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafiante', to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início das férias')),
                ('data_fim', models.DateField(verbose_name='Fim das férias')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='PosicaoLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.SmallIntegerField(verbose_name='Posição atual')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='LutaLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Luta')),
                ('registro_ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.RegistroLadder')),
            ],
        ),
        migrations.CreateModel(
            name='JogadorLuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('luta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Luta')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Personagem')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.SmallIntegerField(verbose_name='Mês')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('posicao', models.SmallIntegerField(verbose_name='Posição no mês')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
    ]
