# Generated by Django 2.2 on 2019-04-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_stage'),
        ('ladder', '0002_auto_20190414_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='luta',
            name='adicionada_por',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='criador_luta', to='jogadores.Jogador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroladder',
            name='adicionada_por',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='criador_registro', to='jogadores.Jogador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luta',
            name='ganhador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhador_luta', to='jogadores.Jogador'),
        ),
    ]
