# Generated by Django 2.2 on 2019-04-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0008_auto_20190421_0806'),
        ('ladder', '0002_auto_20190421_0806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inicioladder',
            unique_together={('posicao',), ('jogador',)},
        ),
        migrations.AlterUniqueTogether(
            name='posicaoladder',
            unique_together={('posicao',), ('jogador',)},
        ),
    ]
