# Generated by Django 2.2 on 2019-04-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0005_auto_20190414_1335'),
        ('ladder', '0003_auto_20190414_0241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicoladder',
            unique_together={('posicao', 'mes', 'ano'), ('jogador', 'mes', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='jogadorluta',
            unique_together={('jogador', 'luta')},
        ),
        migrations.AlterUniqueTogether(
            name='lutaladder',
            unique_together={('registro_ladder', 'luta')},
        ),
        migrations.AlterUniqueTogether(
            name='posicaoladder',
            unique_together={('posicao', 'jogador')},
        ),
        migrations.AlterUniqueTogether(
            name='registroferias',
            unique_together={('jogador', 'data_fim'), ('jogador', 'data_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='registroladder',
            unique_together={('desafiante', 'desafiado', 'data_hora')},
        ),
    ]
