# Generated by Django 2.2 on 2019-04-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_auto_20190414_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroFerias',
        ),
    ]
