# Generated by Django 2.2 on 2019-05-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0011_stagevalidaladder'),
        ('ladder', '0004_auto_20190505_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='desafioladder',
            unique_together={('desafiado', 'data_hora'), ('desafiante', 'data_hora')},
        ),
    ]
