# Generated by Django 2.2 on 2019-04-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0005_delete_registroferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadorluta',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogadores.Personagem'),
        ),
        migrations.AlterField(
            model_name='luta',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogadores.Stage'),
        ),
    ]
