# Generated by Django 2.2 on 2019-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_resultadodesafioladder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadodesafioladder',
            name='progresso',
        ),
        migrations.AddField(
            model_name='resultadodesafioladder',
            name='alteracao_posicao',
            field=models.SmallIntegerField(default=0, verbose_name='Alteração na posição após desafio'),
            preserve_default=False,
        ),
    ]
