# Generated by Django 2.2 on 2019-04-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_auto_20190414_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroladder',
            old_name='adicionada_por',
            new_name='adicionado_por',
        ),
    ]
