# Generated by Django 2.2 on 2019-05-16 16:42

from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0008_auto_20190513_0142'),
        ('jogadores', '0011_stagevalidaladder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemocaoJogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', smashLadder.utils.DateTimeFieldTz(verbose_name='Data/hora da remoção')),
                ('admin_removedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_removedor', to='jogadores.Jogador')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('posicao_jogador', models.SmallIntegerField(default=0, verbose_name='Posição durante remoção')),
            ],
        ),
    ]
