# Generated by Django 2.2 on 2019-04-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0008_auto_20190415_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutaladder',
            name='luta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ladder.Luta'),
        ),
    ]
