# Generated by Django 2.2 on 2019-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0011_stagevalidaladder'),
        ('ladder', '0009_remocaojogador_squashed_0011_auto_20190516_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remocaojogador',
            name='posicao_jogador',
            field=models.SmallIntegerField(verbose_name='Posição durante remoção'),
        ),
        migrations.AlterUniqueTogether(
            name='remocaojogador',
            unique_together={('jogador', 'data')},
        ),
    ]
