# Generated by Django 2.2 on 2019-04-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0006_registroferias'),
        ('ladder', '0009_auto_20190415_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelamentoRegistroLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora da exclusão')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('registro_ladder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ladder.RegistroLadder')),
            ],
        ),
    ]
