# Generated by Django 2.2 on 2019-05-28 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0013_personagem_imagem'),
        ('ladder', '0010_auto_20190516_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remocaojogador',
            name='data',
            field=smashLadder.utils.DateTimeFieldTz(verbose_name='Data da remoção'),
        ),
        migrations.CreateModel(
            name='DecaimentoJogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', smashLadder.utils.DateTimeFieldTz(verbose_name='Data do decaimento')),
                ('posicao_inicial', models.SmallIntegerField(verbose_name='Posição da qual jogador caiu')),
                ('posicao_final', models.SmallIntegerField(verbose_name='Posição para qual jogador caiu')),
                ('qtd_meses_inatividade', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Quantidade de meses inativo')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
            options={
                'unique_together': {('jogador', 'data')},
            },
        ),
    ]
