# Generated by Django 2.2 on 2019-04-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0011_inicioladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutaladder',
            name='indice_registro_ladder',
            field=models.SmallIntegerField(default=0, verbose_name='Índice da luta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lutaladder',
            unique_together={('registro_ladder', 'indice_registro_ladder'), ('registro_ladder', 'luta')},
        ),
    ]
