# Generated by Django 2.2 on 2019-05-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0013_personagem_imagem'),
        ('ladder', '0012_auto_20190528_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decaimentojogador',
            name='posicao_final',
        ),
        migrations.CreateModel(
            name='ResultadoDecaimentoJogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteracao_posicao', models.SmallIntegerField(verbose_name='Alteração na posição após decaimento')),
                ('decaimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.DecaimentoJogador')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
            options={
                'unique_together': {('decaimento', 'jogador')},
            },
        ),
    ]
