# Generated by Django 2.2 on 2019-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0013_auto_20190528_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='remocaojogador',
            name='remocao_por_inatividade',
            field=models.BooleanField(default=False, verbose_name='Remoção devido a inatividade?'),
        ),
    ]
