# Generated by Django 2.2 on 2019-06-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0013_personagem_imagem'),
        ('ladder', '0014_remocaojogador_remocao_por_inatividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoRemocaoJogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteracao_posicao', models.SmallIntegerField(verbose_name='Alteração na posição após remoção')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('remocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.RemocaoJogador')),
            ],
            options={
                'unique_together': {('remocao', 'jogador')},
            },
        ),
    ]
