# Generated by Django 2.2 on 2019-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0017_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lockdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valido', models.BooleanField(default=False, verbose_name='Lockdown válido?')),
            ],
        ),
    ]
