# Generated by Django 2.2 on 2019-12-30 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0020_auto_20191230_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonposicaoinicial',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='season_posicao_inicial', to='ladder.Season'),
            preserve_default=False,
        ),
    ]
