# Generated by Django 2.2 on 2020-01-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0021_auto_20191230_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafioladder',
            options={'ordering': ('data_hora',)},
        ),
    ]
