# Generated by Django 2.2 on 2019-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do estágio')),
                ('modelo', models.SmallIntegerField(choices=[(1, 'Normal'), (2, 'Battlefield'), (3, 'Omega')], verbose_name='Modelo do estágio')),
            ],
        ),
    ]
