# Generated by Django 2.2 on 2019-04-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name_plural': 'jogadores'},
        ),
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name_plural': 'personagens'},
        ),
        migrations.RenameField(
            model_name='jogador',
            old_name='ultimo_uso_corinda',
            new_name='ultimo_uso_coringa',
        ),
    ]
