# Generated by Django 2.2 on 2019-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_auto_20190414_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='ultimo_uso_coringa',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Último uso de coringa'),
        ),
    ]
