# Generated by Django 2.2 on 2019-04-14 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0005_auto_20190414_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início das férias')),
                ('data_fim', models.DateField(verbose_name='Fim das férias')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
            options={
                'unique_together': {('jogador', 'data_inicio'), ('jogador', 'data_fim')},
            },
        ),
    ]
