# Generated by Django 2.2 on 2019-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0007_auto_20190417_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='modelo',
            field=models.SmallIntegerField(choices=[(1, 'Padrão'), (2, 'BF'), (3, 'Omega')], verbose_name='Modelo do estágio'),
        ),
    ]
