# Generated by Django 2.2 on 2019-04-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0008_auto_20190421_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroferias',
            options={'verbose_name_plural': 'registros de férias'},
        ),
    ]
