# Generated by Django 2.2 on 2019-04-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0009_auto_20190422_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='icone',
            field=models.CharField(default='', max_length=50, verbose_name='Ícone'),
            preserve_default=False,
        ),
    ]
