# Generated by Django 2.2 on 2019-04-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0010_personagem_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageValidaLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Stage')),
            ],
        ),
    ]
