# Generated by Django 2.2 on 2019-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0011_stagevalidaladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagevalidaladder',
            name='retorno',
            field=models.BooleanField(default=False, verbose_name='Stage para retorno'),
        ),
    ]
