# Generated by Django 2.2 on 2019-05-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0012_stagevalidaladder_retorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='imagem',
            field=models.CharField(default=' ', max_length=50, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
