# Generated by Django 2.2 on 2019-06-16 18:21

from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0013_personagem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250, verbose_name='Texto do feedback')),
                ('data_hora', smashLadder.utils.DateTimeFieldTz(verbose_name='Data e hora do feedback')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliado', to='jogadores.Jogador')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to='jogadores.Jogador')),
            ],
        ),
    ]
