# Generated by Django 2.2 on 2019-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='nick',
            field=models.CharField(max_length=30, verbose_name='Tag'),
        ),
    ]
