# Generated by Django 2.2 on 2019-12-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0015_auto_20190918_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroFerias',
        ),
    ]
