# Generated by Django 2.2 on 2020-01-07 04:48

from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0016_delete_registroferias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000, verbose_name='Texto do feedback')),
                ('data_hora', smashLadder.utils.DateTimeFieldTz(auto_now_add=True, verbose_name='Data e hora da sugestão')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
    ]
