# Generated by Django 2.2 on 2020-01-07 05:12

from django.db import migrations, models
import smashLadder.utils


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0017_sugestaoladder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='data_hora',
            field=smashLadder.utils.DateTimeFieldTz(auto_now_add=True, verbose_name='Data e hora do feedback'),
        ),
        migrations.AlterField(
            model_name='sugestaoladder',
            name='texto',
            field=models.CharField(max_length=1000, verbose_name='Texto da sugestão'),
        ),
    ]
