# Generated by Django 2.2 on 2019-09-04 23:59

from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogadores', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRequisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_requisicao', smashLadder.utils.DateTimeFieldTz(verbose_name='Data/hora da requisição')),
                ('data_hora_resposta', smashLadder.utils.DateTimeFieldTz(verbose_name='Data/hora da resposta')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
    ]
