# Generated by Django 2.2 on 2019-10-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performancerequisicao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancerequisicao',
            name='jogador',
        ),
    ]
