# Generated by Django 2.2 on 2020-01-13 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_remove_performancerequisicao_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerequisicao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
