# Generated by Django 2.2 on 2019-09-24 22:01

from django.db import migrations, models
import django.db.models.deletion
import smashLadder.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogadores', '0015_auto_20190918_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da métrica')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTreinamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', smashLadder.utils.DateTimeFieldTz(verbose_name='Data/hora de início')),
                ('fim', smashLadder.utils.DateTimeFieldTz(verbose_name='Data/hora de fim')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTreinamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.Metrica')),
                ('registro_treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.RegistroTreinamento')),
            ],
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250, verbose_name='Texto da anotação')),
                ('data_hora', smashLadder.utils.DateTimeFieldTz(auto_now_add=True, verbose_name='Data/hora da anotação')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
            ],
        ),
    ]
